# Generated by Django 6.1.1 on 2026-10-07 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_dark_mode_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='due_soon_days',
            field=models.PositiveIntegerField(default=7, help_text='Assignments due today through this many days ahead are due soon.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
    ]
