# Generated by Django 6.1.1 on 2026-10-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_sync', '0002_canvasconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='sync_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='sync_status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='success', max_length=20),
        ),
    ]
