# Generated by Django 6.1.1 on 2026-10-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_sync', '0003_assignment_sync_error_message_assignment_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasconnection',
            name='last_synchronized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canvasconnection',
            name='sync_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='canvasconnection',
            name='sync_status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
