# Generated by Django 6.1.1 on 2026-10-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_sync', '0004_canvasconnection_last_synchronized_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
