# Generated by Django 6.1.1 on 2026-10-07 19:19

from django.conf import settings
from django.db import migrations, models


def merge_duplicate_canvas_records(apps, schema_editor):
    Course = apps.get_model("canvas_sync", "Course")
    Assignment = apps.get_model("canvas_sync", "Assignment")
    RubricCriterion = apps.get_model("canvas_sync", "RubricCriterion")

    courses_by_canvas_id = {}
    for course in Course.objects.order_by("pk").iterator():
        key = (course.user_id, course.canvas_course_id)
        canonical_course = courses_by_canvas_id.get(key)
        if canonical_course is None:
            courses_by_canvas_id[key] = course
            continue

        for assignment in Assignment.objects.filter(course=course).iterator():
            canonical_assignment = Assignment.objects.filter(
                course=canonical_course,
                canvas_assignment_id=assignment.canvas_assignment_id,
            ).first()
            if canonical_assignment is None:
                assignment.course = canonical_course
                assignment.save(update_fields=["course"])
            else:
                RubricCriterion.objects.filter(assignment=assignment).update(
                    assignment=canonical_assignment
                )
                assignment.delete()
        course.delete()

    assignments_by_canvas_id = {}
    for assignment in Assignment.objects.order_by("pk").iterator():
        key = (assignment.course_id, assignment.canvas_assignment_id)
        canonical_assignment = assignments_by_canvas_id.get(key)
        if canonical_assignment is None:
            assignments_by_canvas_id[key] = assignment
            continue

        RubricCriterion.objects.filter(assignment=assignment).update(
            assignment=canonical_assignment
        )
        assignment.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_sync', '0005_course_is_visible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rubriccriterion',
            name='canvas_rubric_criterion_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            merge_duplicate_canvas_records,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('course', 'canvas_assignment_id'), name='unique_canvas_assignment_per_course'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('user', 'canvas_course_id'), name='unique_canvas_course_per_user'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.UniqueConstraint(condition=models.Q(('canvas_rubric_criterion_id__isnull', False)), fields=('assignment', 'canvas_rubric_criterion_id'), name='unique_canvas_rubric_criterion_per_assignment'),
        ),
    ]
