# Generated by Django 6.1.1 on 2026-10-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_sync', '0006_assignment_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='last_synchronized_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
