# Generated by Django 6.1.1 on 2026-09-15 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canvas_sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('checklist_generation', 'Checklist generation')], max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('model_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('estimated_minutes', models.PositiveIntegerField(default=30, help_text='Estimated time needed to complete this task.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Position of this task within the assignment checklist.')),
                ('is_completed', models.BooleanField(default=False)),
                ('ai_generated', models.BooleanField(default=True, help_text='True if this task was suggested by the AI, False if the student added it.')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_items', to='canvas_sync.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
